# Identificador único de tu proyecto (puedes inventarlo o copiarlo de Sonar)
sonar.projectKey=tp1-telegram-bot
sonar.projectName=TP1 Telegram Bot

# Dónde está tu código (ajusta si tu código está en una carpeta llamada /src)
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# ¡Aquí es donde ocurre la magia del reporte!
# Le decimos a Sonar que lea el archivo que generó el robot en la fase anterior
sonar.python.coverage.reportPaths=coverage.xml